lane :test do
  android_set_version_code(
    version_code: 17, # optional, if not specified, Version Code will be incremented
    gradle_file: "app/build.gradle.kts" # optional
  )

  android_set_version_name(
    version_name: "1.23.4",
    gradle_file: "app/build.gradle.kts", # optional
  )
end
